version: '3.9'

services:
  app:
    build: .
    command: gunicorn chui_labs.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8085:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=chui_labs.settings
